### ISSUE TITLE
Filters and Sort By features

### ISSUE THREAD

**Issue by thought-train** [Sbrjt/josaa#6]
I noticed that you don't have filters and sort by feaures after searching for the possible colleges.

Let me work on it and send a PL.

Since JoSAA counselling is starting from tomorrow,It'll be helpful to many and I'll try to send the PL by tomorrow,

You can assign me this issue too.

**Comment by Sbrjt** [comment]
Sorry I didn't understand. Can you give me an example?

**Comment by thought-train** [comment]
At one point,I wanted to sort all of them by their branch and then by the institute,but was not able to do that.So,I wanted to build this feature.If I selected both ee and cse branch,but want to see all cse branches first,I can't do that here.Thats what I meant.

**Comment by Sbrjt** [comment]
Out of scope.
